name: xcode - build

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    name: latest macos x
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        uses: mxcl/xcodebuild@v2
        with:
          xcode: ^14
          action: none
      - name: Build
        run: |
          pod install
          xcodebuild -configuration Debug -workspace QuickLookXD.xcworkspace -scheme QuickLookXD clean build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./dist
          publish_branch: dist
          destination_dir: ${{ github.sha }}
          keep_files: true
