name: xcode - build

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    name: latest macos x
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: mxcl/xcodebuild@v2
        with:
          xcode: ^14
          action: build
          configuration: Debug
          verbosity: verbose
