name: xcode - build

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    name: latest macos x
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        uses: mxcl/xcodebuild@v2
        with:
          xcode: ^14
          action: none
      - name: Build
        run: |
          pod install
          xcodebuild -configuration Debug -workspace QuickLookXD.xcworkspace -scheme QuickLookXD clean build -quiet
          
          export PUBLISH_DIR="/tmp/quicklookxdist"
          export ZIP_FILENAME="archive.zip"
          export BUILT_GENERATOR_FILENAME="$(xcodebuild -configuration Debug -workspace QuickLookXD.xcworkspace -scheme QuickLookXD -showBuildSettings 2>&1 | grep CODESIGNING_FOLDER_PATH | cut -d '=' -f2 | tr -d '[:space:]')"
          
          echo "Making folder: ${PUBLISH_DIR}"
          mkdir -p "${PUBLISH_DIR}"
          
          echo "Change directory: ${BUILT_GENERATOR_FILENAME}"
          cd "${BUILT_GENERATOR_FILENAME}/../"
          pwd
          
          echo "Zipping: $(basename '${BUILT_GENERATOR_FILENAME}') >>> ${ZIP_FILENAME}"
          zip -r "${ZIP_FILENAME}" "$(basename ${BUILT_GENERATOR_FILENAME})"
          ls
          
          echo "Copying: ${ZIP_FILENAME} >>> ${PUBLISH_DIR}"
          cp "${ZIP_FILENAME}" "${PUBLISH_DIR}"
          
          ls "${PUBLISH_DIR}"
          echo "PUBLISH_DIR=${PUBLISH_DIR}" >> "$GITHUB_ENV"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ${{ env.PUBLISH_DIR }}
          publish_branch: dist
          destination_dir: ${{ github.sha }}
          keep_files: true
